version: 2
models:
  - name: stg_coingecko__asset_info
    tags: [stg]
    description: "Asset info with columns names and types updated"
    columns:
      - name: asset
        tests: [not_null]
      - name: category_type
        tests:
          - accepted_values: {values: ['altcoin','stablecoin','bitcoin']}

  - name: stg_binance__exchange_info
    tags: [stg]
    description: "Exchange info with columns names and types updated and filtered on active symbol"
    columns:
      - name: symbol
        tests: [not_null, unique]
      - name: base_asset
        tests: [not_null]
      - name: quote_asset
        tests: [not_null]
  
  - name: stg_binance__kline
    tags: [stg]
    description: "Kline data with columns names and types updated"
    columns:
      - name: id
        tests: [not_null, unique]
      - name: symbol
        tests: [not_null]
      - name: open_time
        tests: [not_null]
      - name: close_time
        tests: [not_null]
      - name: open_price
        tests: [not_null]
      - name: high_price
        tests: [not_null]
      - name: low_price
        tests: [not_null]
      - name: close_price
        tests: [not_null]
      - name: volume
        tests: [not_null]
      - name: quote_asset_volume
        tests: [not_null]
      - name: number_of_trades
        tests: [not_null]
      - name: taker_buy_base_asset_volume
        tests: [not_null]
      - name: taker_buy_quote_asset_volume
        tests: [not_null]
    
  - name: stg_calendar__calendar
    tags: [tags]
    description: "calendar data with no change since the stage table"
    columns:
      - name: date_full
        tests: [not_null, unique]