version: 2

models:

  - name: dim_calendar
    description: "Dimension calendrier (1 ligne par jour)."
    columns:
      - name: date_full
        tests: [not_null, unique]
      - name: year
        tests: [not_null]
      - name: month
        tests:
          - not_null
          - accepted_values:
              values: [1,2,3,4,5,6,7,8,9,10,11,12]

  - name: dim_symbol
    description: "Info sur les paires Binance (grain = 1 ligne par symbole, actifs uniquement)."
    columns:
      - name: symbol
        tests: [not_null, unique]
      - name: base_asset
        tests:
          - not_null
          - relationships:
              to: ref('dim_base_asset')
              field: base_asset
      - name: quote_asset
        tests:
          - not_null
          - relationships:
              to: ref('dim_quote_asset')
              field: quote_asset
      - name: last_updated
        tests: [not_null]

  - name: dim_base_asset
    description: "Information sur le base asset (listés Binance et enrichis Coingecko)."
    columns:
      - name: base_asset
        tests: [not_null, unique]
      - name: base_asset_name
        tests: [not_null]
      - name: coingecko_id
        tests: [not_null, unique]
      - name: market_cap_rank
        tests: [non_negative]
      - name: token_type
      - name: supply_circulating
        tests: [non_negative]
      - name: supply_total
        tests: [non_negative]
      - name: supply_max
        tests: [non_negative]
      - name: category_type
        tests:
          - accepted_values:
              values: ['altcoin','stablecoin','bitcoin']
      - name: has_max_supply
      - name: has_total_supply
      - name: pct_of_max_supply
        tests: [non_negative]
      - name: pct_of_total_supply
        tests: [non_negative]
      - name: locked_supply
        tests: [non_negative]
      - name: pct_locked
        tests: [non_negative]
      - name: last_updated
        tests: [not_null]

  - name: dim_quote_asset
    description: "Information sur le quote asset (listés Binance et enrichis Coingecko)."
    columns:
      - name: quote_asset
        tests: [not_null, unique]
      - name: quote_asset_name
        tests: [not_null]
      - name: coingecko_id
        tests: [not_null, unique]
      - name: market_cap_rank
        tests: [non_negative]
      - name: token_type
      - name: supply_circulating
        tests: [non_negative]
      - name: supply_total
        tests: [non_negative]
      - name: supply_max
        tests: [non_negative]
      - name: category_type
        tests:
          - accepted_values:
              values: ['altcoin','stablecoin','bitcoin']
      - name: has_max_supply
      - name: has_total_supply
      - name: pct_of_max_supply
        tests: [non_negative]
      - name: pct_of_total_supply
        tests: [non_negative]
      - name: locked_supply
        tests: [non_negative]
      - name: pct_locked
        tests: [non_negative]
      - name: last_updated
        tests: [not_null]

  - name: fact_klines
    description: "Bougies Binance agrégées par jour (grain = 1 jour x symbole)."
    columns:
      - name: symbol
        tests:
          - not_null
          - relationships:
              to: ref('dim_symbol')
              field: symbol
      - name: base_asset
        tests:
          - not_null
          - relationships:
              to: ref('dim_base_asset')
              field: base_asset
      - name: quote_asset
        tests:
          - not_null
          - relationships:
              to: ref('dim_quote_asset')
              field: quote_asset
      - name: date_jour
        tests:
          - not_null
          - relationships:
              to: ref('dim_calendar')
              field: date_full
      - name: close_price
        tests: [non_negative]
      - name: volume
        tests: [non_negative]
      - name: number_of_trades
        tests: [non_negative]
      - name: avg_vol_7d
        tests: [non_negative]
      - name: avg_vol_30d
        tests: [non_negative]
      - name: avg_trades_7d
        tests: [non_negative]
      - name: avg_trades_30d
        tests: [non_negative]
      - name: vol_ytd_total
        tests: [non_negative]
      - name: vol_ytd_avg
        tests: [non_negative]
      - name: trades_ytd_total
        tests: [non_negative]
      - name: trades_ytd_avg
        tests: [non_negative]
      - name: last_updated
        tests: [not_null]