opa_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: hbvyxoa-li66752
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: DBT
      schema: STAGING
      threads: 4
      client_session_keep_alive: false